spring:
  kafka:
    bootstrap-servers : localhost:9092
    topic-name : emps
  application:
      name: discover-server
server:
    port: 8761

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/