server:
  port: 8761
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/company_uat
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          lob:
            non_contextual_creation: true

  kafka:
    bootstrap-servers : localhost:9093
    topic-name : emps
  application:
      name: discover-server
